/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author manan
 */import java.awt.event.*;
import javax.swing.ImageIcon;
public class Menu extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        AddUserMenuItem.addActionListener((ActionListener) this);
        ExitMenuItem.addActionListener((ActionListener) this);
        jMenuItem3.addActionListener((ActionListener) this);
        jMenuItem4.addActionListener((ActionListener) this);
        ClubMenuItem.addActionListener((ActionListener) this);
        EventMenuItem.addActionListener((ActionListener) this);
        MembershipsMenuItem.addActionListener((ActionListener) this);
        ParticipationshipMenuItem.addActionListener((ActionListener) this);
        VolunteershipMenuItem.addActionListener((ActionListener) this);
        ResultsMenuItem.addActionListener((ActionListener) this);
        MemberReportMenuItem.addActionListener((ActionListener) this);
        ParticipationReportMenuItem.addActionListener((ActionListener) this);
        VolunteerMenuItem.addActionListener((ActionListener) this);
        ResultReportMenuItem.addActionListener((ActionListener) this);  
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        if(ae.getSource()==AddUserMenuItem){
            ChangePwd obj1=new ChangePwd();
                obj1.setVisible(true);
        }
        if(ae.getSource()==ExitMenuItem){
            AddUser obj2=new AddUser();
                obj2.setVisible(true);
        }
        if(ae.getSource()==jMenuItem3){
            RemoveUser obj3=new RemoveUser();
                obj3.setVisible(true);
        }
        if(ae.getSource()==jMenuItem4){
            ChangePwd obj4=new ChangePwd();
                obj4.setVisible(true);
        }
        if(ae.getSource()==ClubMenuItem){
            club obj5=new club();
                obj5.setVisible(true);
        }
        if(ae.getSource()== EventMenuItem){
            Event obj6=new Event();
                obj6.setVisible(true);
        }
        if(ae.getSource()==MembershipsMenuItem){
            Register obj7=new Register();
                obj7.setVisible(true);
        }
        if(ae.getSource()==ParticipationshipMenuItem){
            Participant obj8=new Participant();
                obj8.setVisible(true);
        }
        if(ae.getSource()==VolunteershipMenuItem){
             Volunteer obj9=new Volunteer();
                obj9.setVisible(true);
        }
        if(ae.getSource()==ResultsMenuItem){
            Prize obj10=new Prize();
                obj10.setVisible(true);
        }
        if(ae.getSource()==MemberReportMenuItem){
            MemberReports obj11=new MemberReports();
                obj11.setVisible(true);
        }
        if(ae.getSource()==ParticipationReportMenuItem){
             ParticipationReport obj12=new ParticipationReport();
                obj12.setVisible(true);
        }
        if(ae.getSource()==VolunteerMenuItem){
            VolunteerReport obj13=new VolunteerReport();
                obj13.setVisible(true);
        }
        if(ae.getSource()==ResultReportMenuItem){
            ResultReport obj14=new ResultReport();
                obj14.setVisible(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IconLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ChangePwdMenuItem = new javax.swing.JMenu();
        AddUserMenuItem = new javax.swing.JMenuItem();
        ExitMenuItem = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ClubMenuItem = new javax.swing.JMenuItem();
        EventMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MembershipsMenuItem = new javax.swing.JMenuItem();
        ParticipationshipMenuItem = new javax.swing.JMenuItem();
        VolunteershipMenuItem = new javax.swing.JMenuItem();
        ResultsMenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MemberReportMenuItem = new javax.swing.JMenuItem();
        ParticipationReportMenuItem = new javax.swing.JMenuItem();
        VolunteerMenuItem = new javax.swing.JMenuItem();
        ResultReportMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clubs.png"))); // NOI18N

        ChangePwdMenuItem.setText("Admin");

        AddUserMenuItem.setText("Change Password");
        AddUserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserMenuItemActionPerformed(evt);
            }
        });
        ChangePwdMenuItem.add(AddUserMenuItem);

        ExitMenuItem.setText("Add User");
        ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuItemActionPerformed(evt);
            }
        });
        ChangePwdMenuItem.add(ExitMenuItem);

        jMenuItem3.setText("Remove User");
        ChangePwdMenuItem.add(jMenuItem3);

        jMenuItem4.setText("Exit");
        ChangePwdMenuItem.add(jMenuItem4);

        jMenuBar1.add(ChangePwdMenuItem);

        jMenu2.setText("Master");

        ClubMenuItem.setText("Club");
        jMenu2.add(ClubMenuItem);

        EventMenuItem.setText("Event");
        jMenu2.add(EventMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Processes");

        MembershipsMenuItem.setText("Memberships");
        MembershipsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MembershipsMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(MembershipsMenuItem);

        ParticipationshipMenuItem.setText("Participationships");
        jMenu3.add(ParticipationshipMenuItem);

        VolunteershipMenuItem.setText("Volunteerships");
        jMenu3.add(VolunteershipMenuItem);

        ResultsMenuItem.setText("Results");
        ResultsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultsMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(ResultsMenuItem);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Reports");

        MemberReportMenuItem.setText("Membership Reports");
        jMenu4.add(MemberReportMenuItem);

        ParticipationReportMenuItem.setText("Participation Reports");
        jMenu4.add(ParticipationReportMenuItem);

        VolunteerMenuItem.setText("Volunteer Reports");
        VolunteerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolunteerMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(VolunteerMenuItem);

        ResultReportMenuItem.setText("Result Reports");
        jMenu4.add(ResultReportMenuItem);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1669, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddUserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddUserMenuItemActionPerformed

    private void ExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitMenuItemActionPerformed

    private void MembershipsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MembershipsMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MembershipsMenuItemActionPerformed

    private void ResultsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultsMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultsMenuItemActionPerformed

    private void VolunteerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolunteerMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolunteerMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddUserMenuItem;
    private javax.swing.JMenu ChangePwdMenuItem;
    private javax.swing.JMenuItem ClubMenuItem;
    private javax.swing.JMenuItem EventMenuItem;
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JLabel IconLabel;
    private javax.swing.JMenuItem MemberReportMenuItem;
    private javax.swing.JMenuItem MembershipsMenuItem;
    private javax.swing.JMenuItem ParticipationReportMenuItem;
    private javax.swing.JMenuItem ParticipationshipMenuItem;
    private javax.swing.JMenuItem ResultReportMenuItem;
    private javax.swing.JMenuItem ResultsMenuItem;
    private javax.swing.JMenuItem VolunteerMenuItem;
    private javax.swing.JMenuItem VolunteershipMenuItem;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
